name: ISSUE TEMPLATE
description: File a ISSUE TEMPLATE
title: '[ISSUE]: '

body:
  - type: markdown
    attributes:
      value: |
        REBADGEME ISSUE TEMPLATE입니다!

  - type: textarea
    id: title
    attributes:
      label: ✨ 작업 내용
      description: 해야할 작업에 대해서 간단하게 적어주세요
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: ⚙ 상새한 작업 내용
      description: 상새한 작업 내용을 적어주세요
      value: '- [ ] :

        - [ ] :

        - [ ] : '
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: 🛠 예상 소요시간
      multiple: false
      options:
        - 하루 이상
        - 12시간 이내
        - 5시간 이내
        - 3시간 이내
        - 1시간 이내
        - 30분 이내
